steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'VITE_VERTEX_API_KEY=${_VITE_VERTEX_API_KEY}'
      - '--build-arg'
      - 'VITE_VERTEX_PROJECT=smiling-gasket-494406-p1'
      - '--build-arg'
      - 'VITE_VERTEX_LOCATION=global'
      - '-t'
      - 'asia-south1-docker.pkg.dev/smiling-gasket-494406-p1/cloud-run-source-deploy/mayas-mirror:latest'
      - '.'
images:
  - 'asia-south1-docker.pkg.dev/smiling-gasket-494406-p1/cloud-run-source-deploy/mayas-mirror:latest'
